apiVersion: v1
kind:  Pod
metadata:
  name: frontend
spec:
  containers:
    - name: nginx
      image: madhanmohanreddyeeda/github-repo-frontend
      ports:
        - containerPort: 80
          hostport: 10000

