apiVersion: v1
kind:  Pod
metadata:
  name: frontend
spec:
  containers:
    - name: nginx
      image: madhanmohanreddyeeda/github-repo-frontend

---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
spec:
  initContainers:
    - name: parameters-pull
      image: docker.io/madhanmohanreddyeeda/github-repo-parameter-store-init-container-image
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /parameters
          name: parameters
      env:
        - name: PARAMS
          value: "dev.roboshop.catalogue.MONGO_URL,MONGO_URL"
  containers:
    - name: catalogue
      image: madhanmohanreddyeeda/github-repo-catalogue
      volumeMounts:
      - mountPath: /parameters
        name: parameters
  volumes:
    - name: parameters
      emptyDir: {}


---
apiVersion: v1
kind: Pod
metadata:
  name: cart
spec:
  containers:
    - name: cart
      image: madhanmohanreddyeeda/github-repo-cart

---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
spec:
  containers:
    - name: shipping
      image: madhanmohanreddyeeda/github-repo-shipping

---
apiVersion: v1
kind: Pod
metadata:
  name: payment
spec:
  containers:
    - name: payment
      image: madhanmohanreddyeeda/github-repo-payment

---
apiVersion: v1
kind: Pod
metadata:
  name: dispatch
spec:
  containers:
    - name: dispatch
      image: madhanmohanreddyeeda/github-repo-dispatch

---
apiVersion: v1
kind: Pod
metadata:
  name: user
spec:
  containers:
    - name: user
      image: madhanmohanreddyeeda/github-repo-user



